- id: run_moss
  uses: PurdueECE/action-moss@main
  # MOSS system user ID
  # Required
  user_id: 
  # usage: file1 file2 file3 ... [-l language] [-d] [-b basefile1] ... [-b basefilen] [-m #] [-c "string"]
  # Required
  arguments: file1.py -l 'python'
# Print URL of generated report
- run: echo 'MOSS Report URL = ${{ steps.run_moss.outputs.url }}'
